### ISSUE TITLE
Facturas quedan en estado confirmadas luego de pagarlas con recibos

### ISSUE THREAD

**Issue by lukio** [tryton-ar/account_voucher_ar#3]
Por alguna razón, luego de confirmar un recibo, la factura continua en estado confirmada y no pasa a estado pagada. Compruebo que se ha realizado el asiento de pago. ¿Hay algo más que debería de suceder para que el estado de la factura pase a pagada?

**Comment by smarro** [comment]
Lukio, ingresaste el importe a pagar en la columna de Saldando ? La factura pasa a estado pagada cuando las líneas contables se concilian con las líneas contables del asiento del recibo.

**Comment by lukio** [comment]
Hola Seba, gracias por responder tan rápido. Te adjunto capturas de pantalla del recibo y de la factura. Y sí, agregué el monto en la columna Saldando. 

**Recibo**:
![captura de pantalla de 2017-04-25 12 08 03](https://cloud.githubusercontent.com/assets/776682/25392944/7a790c6a-29b0-11e7-9aea-28808a89c36f.png)

**Factura de proveedor todavía en estado pagada**
![captura de pantalla de 2017-04-25 12 07 01](https://cloud.githubusercontent.com/assets/776682/25392946/7a9352b4-29b0-11e7-8aef-6bb5a797d0ab.png)

**Factura de proveedor. Pestaña pagos.**
Tenemos instalado el módulo _account_invoice_visible_payments_ de trytonspain para ver las lineas de los pagos
![captura de pantalla de 2017-04-25 12 06 54](https://cloud.githubusercontent.com/assets/776682/25392945/7a81e2e0-29b0-11e7-8b12-09f16bb218cf.png)

**Comment by lukio** [comment]
@smarro luego de probar mucho, creo haber encontrado el bug.

1. Cree una factura de proveedor y la pase a estado validada.
2. Cree un recibo de pago, cargue a la entidad en cuestión y me apareció listada como factura pendiente la que estaba en estado validada. 
3. Cargué el recibo completo y clickee botón pagar.

Resultado:

La factura siguió en estado validada y conciliada. 

4. Me dejó pasar la factura a estado Confirmada. En la pestaña de pago, apareció el movimiento generado por el recibo anterior.

Adjunto capturas.

**Factura validada:**
![captura de pantalla de 2017-05-04 11 25 03](https://cloud.githubusercontent.com/assets/776682/25708964/5f657de0-30be-11e7-8f24-b9e7de1e0eb4.png)

**Aparece como factura pendiente, una que esta en estado validada:**
![captura de pantalla de 2017-05-04 11 25 16](https://cloud.githubusercontent.com/assets/776682/25708963/5f653ede-30be-11e7-9680-7f5ba8855f53.png)

**Comment by lukio** [comment]
Bueno, cuando se agregan las lineas de facturas pendientes, se obtienen de las lineas de asientos que estan en estado **valid**. El problema es que no chequea que el asiento este en estado **posted** ( o sea, factura confirmada).

https://github.com/tryton-ar/account_voucher_ar/blob/master/account_voucher_ar.py#L312
